<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../../build/packages.props" />

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Process\Kaleido.Process.csproj" />
	</ItemGroup>

</Project>
