<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../build/tests.props" />
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
        <ProjectReference Include="..\..\..\src\Process\Process\Kaleido.Process.csproj" />
  </ItemGroup>

</Project>
