<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Kaleido.Queryable.AspNetCore</RootNamespace>
		<AssemblyName>Kaleido.Queryable.AspNetCore</AssemblyName>
		<PackageId>Kaleido.Queryable.AspNetCore</PackageId>
		<Version>1.0.0</Version>
		<Authors>Andrew Ross</Authors>
		<Company>Andrew Ross</Company>
		<Description>Metadata-driven queryable reference data framework.</Description>
		<RepositoryUrl>https://github.com/andrew-ross-elv/Kaleido</RepositoryUrl>
		<PackageTags>reference-data;metadata;query;framework</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\src\Queryable\Kaleido.Queryable.csproj" />
	</ItemGroup>

</Project>
