<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../build/packages.props" />

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\Kaleido\Kaleido.csproj" />
	  <ProjectReference Include="..\Abstractions\Kaleido.Process.Abstractions.csproj" />
	</ItemGroup>

</Project>
