using System.Text.Json.Serialization;

namespace Kaleido.Process.Participant;

/// <summary>
/// Represents the outcome of a process step after execution
/// or evaluation by the process runtime.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum StepExecutionOutcome
{
    /// <summary>
    /// The step has not yet been evaluated or executed.
    /// </summary>
    Pending,

    /// <summary>
    /// The step completed successfully.
    /// </summary>
    Completed,

    /// <summary>
    /// The step executed but did not complete successfully.
    /// </summary>
    Failed,

    /// <summary>
    /// The step could not be executed because one or more
    /// required prerequisites were not satisfied.
    /// </summary>
    Blocked,

    /// <summary>
    /// The step was intentionally stopped and will not continue.
    /// </summary>
    Cancelled
}

/// <summary>
/// Represents the processing status of a specific step request
/// recorded in the participant execution history.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum StepExecutionStatus
{
    /// <summary>
    /// The request has not yet been processed.
    /// </summary>
    Pending,

    /// <summary>
    /// The request was processed successfully.
    /// </summary>
    Completed,

    /// <summary>
    /// The request failed validation and was never executed.
    /// </summary>
    ValidationFailed,

    /// <summary>
    /// An unexpected exception occurred while processing the request.
    /// </summary>
    Exception,

    Skipped,
    Canceled
}

/// <summary>
/// Indicates the severity of a planning, validation,
/// or diagnostic message generated by the framework.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum MessageType
{
    /// <summary>
    /// Informational message that does not affect planning
    /// or execution.
    /// </summary>
    Information,

    /// <summary>
    /// Warning message indicating a potential issue that
    /// does not prevent processing.
    /// </summary>
    Warning,

    /// <summary>
    /// Error message indicating a condition that prevents
    /// the candidate from being included in the execution plan.
    /// </summary>
    Error
}

/// <summary>
/// Identifies the specific condition that generated a
/// planning, validation, or consistency diagnostic message.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum StepProcessingMessageCode
{
    /// <summary>
    /// A requested step does not exist in the process registry.
    /// </summary>
    UnknownStep,

    /// <summary>
    /// The supplied request is invalid and could not be processed.
    /// </summary>
    InvalidRequest,

    /// <summary>
    /// A required property could not be found on the step request.
    /// </summary>
    PropertyNotFound,

    /// <summary>
    /// A value could not be converted to the expected type.
    /// </summary>
    ConversionFailed,

    /// <summary>
    /// Candidate validation failed and the step cannot participate
    /// in execution planning.
    /// </summary>
    ValidationFailed,

    /// <summary>
    /// The step was previously completed and does not require
    /// additional processing.
    /// </summary>
    AlreadyProcessed,

    /// <summary>
    /// A consistency rule was violated during candidate evaluation.
    /// </summary>
    ConsistencyViolation,

    /// <summary>
    /// One or more required dependencies have not been satisfied.
    /// </summary>
    DependencyNotSatisfied,

    /// <summary>
    /// All required dependencies have been satisfied.
    /// </summary>
    DependencySatisfied,

    HandlerExecutionFailed,
    ExceptionThrown,
    InvalidRequiredStep,
    RequiredStepNotAllowed,
    ExecutionCancelled,
    FrameworkException,
    ProcessMessage,
    RepeatableStep
}