<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
		<RootNamespace>Kaleido.Http</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Kaleido\Kaleido.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Kaleido.Http.Abstractions.UnitTests" />
	</ItemGroup>

</Project>
