<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../build/samples.props" />

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
	</ItemGroup>

  <ItemGroup>
    <None Remove="functional-records.csv" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="functional-records.csv">
		<Link>data\functional-records.csv</Link>
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Queryable\Queryable\Kaleido.Queryable.csproj" />
  </ItemGroup>


</Project>
