<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
		<ProjectReference Include="..\Kaleido\Kaleido.csproj" />
		<ProjectReference Include="..\Kaleido.Http.Abstractions\Kaleido.Http.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
	</ItemGroup>

</Project>
