namespace Kaleido.Eventing;

/// <summary>
/// Correlation and traceability context attached to every process domain event.
/// Populated by the framework from the active <see cref="Kaleido.Observability.KaleidoCorrelationContext"/>
/// and <see cref="KaleidoServiceOptions"/> at event creation time.
/// </summary>
public sealed record ProcessEventContext
{
    /// <summary>
    /// The unique identifier of the originating request.
    /// Always populated — generated by the framework if not supplied by the caller via <c>X-Kaleido-Request-Id</c>.
    /// Pass the same value on all service calls in a user action to correlate events across service boundaries.
    /// </summary>
    public required string RequestId { get; init; }

    /// <summary>The service that emitted this event, from <see cref="KaleidoServiceOptions.ServiceName"/>.</summary>
    public required string ServiceName { get; init; }

    /// <summary>The process instance this event belongs to.</summary>
    public required Guid ProcessId { get; init; }

    /// <summary>The step that was executing when this event was emitted.</summary>
    public required string StepName { get; init; }

    /// <summary>
    /// The stable instance identifier of the service that produced this event.
    /// Always from <see cref="KaleidoServiceOptions.InstanceId"/> — never from an inbound header.
    /// </summary>
    public string? ProcessorInstanceId { get; init; }

    /// <summary>
    /// The service name of the caller that originated this request, if propagated via <c>X-Kaleido-Source-Processor</c>.
    /// Falls back to <see cref="ServiceName"/> when not present.
    /// </summary>
    public string? SourceProcessorName { get; init; }
}
