<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../build/packages.props" />

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\..\Core\AspNetCore\Kaleido.AspNetCore.csproj" />
	  <ProjectReference Include="..\Process\Kaleido.Process.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="OpenTelemetry" Version="1.18.0" />
	</ItemGroup>

</Project>
