namespace Kaleido.Observability;

public sealed record KaleidoCorrelationContext
{
    /// <summary>
    /// The unique identifier of the originating request.
    /// Always non-empty — generated by the framework if not supplied by the caller via <c>X-Kaleido-Request-Id</c>.
    /// </summary>
    public string RequestId
    {
        get;
        init;
    } = string.Empty;

    public Guid? ProcessId
    {
        get;
        init;
    }

    public Guid? ProcessorInstanceId
    {
        get;
        init;
    }

    public string? SourceProcessorName
    {
        get;
        init;
    }

    /// <summary>
    /// The name of the process step making the current inter-service call, if propagated via <c>X-Kaleido-Step-Name</c>.
    /// Populated on queryable services when a process step calls them, enabling step-level traceability.
    /// </summary>
    public string? StepName
    {
        get;
        init;
    }

    /// <summary>
    /// Returns <c>true</c> when the correlation context has no meaningful correlation fields set —
    /// indicating no correlation context has been established for the current request.
    /// </summary>
    public bool IsEmpty =>
        string.IsNullOrWhiteSpace(RequestId)
        && ProcessId is null
        && ProcessorInstanceId is null
        && string.IsNullOrWhiteSpace(SourceProcessorName);
}

public interface IKaleidoCorrelationContextAccessor
{
    KaleidoCorrelationContext Current
    {
        get;
    }
}
