services:
  eventcollector:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  referencedata:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  codeset:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  configuration:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  provider:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  member:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  history:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  router:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  intake:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  radiology:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
