<Project Sdk="Microsoft.NET.Sdk.Web">
<ItemGroup>
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.*" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="functional-records.csv" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="functional-records.csv">
			<Link>data\functional-records.csv</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Kaleido.Http\Kaleido.Http.csproj" />
	</ItemGroup>

</Project>
