<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../build/samples.props" />
	<PropertyGroup>
		<RootNamespace>Kaleido.Samples.PriorAuth.History</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../../src/Process/AspNetCore.Client/Kaleido.Process.AspNetCore.Client.csproj" />
		<ProjectReference Include="../../../src/Queryable/AspNetCore.Client/Kaleido.Queryable.AspNetCore.Client.csproj" />
		<ProjectReference Include="../Common/Kaleido.Samples.PriorAuth.Common.csproj" />
	</ItemGroup>

</Project>
