<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Kaleido.Http.Abstractions\Kaleido.Http.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Kaleido.Http.UnitTests" />
	</ItemGroup>

</Project>
