<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../build/packages.props" />

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Kaleido\Kaleido.csproj" />
		<ProjectReference Include="..\Kaleido.Http.Abstractions\Kaleido.Http.Abstractions.csproj" />
	</ItemGroup>

</Project>
