<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../build/samples.props" />
	<PropertyGroup>
		<RootNamespace>Kaleido.Samples.ECommerce</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Data\Assets\customers.json" />
	  <None Remove="Data\Assets\suppliers.json" />
	  <None Remove="Data\Assets\taxonomy.json" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Data\Assets\customers.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Data\Assets\suppliers.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Data\Assets\taxonomy.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Process\Abstractions\Kaleido.Process.Abstractions.csproj" />
	  <ProjectReference Include="..\..\src\Queryable\Abstractions\Kaleido.Queryable.Abstractions.csproj" />
	</ItemGroup>


</Project>
