<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
    <UserSecretsId>f1499271-303a-4903-8ddf-d35992c8ba4e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Swashbuckle.AspNetCore" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	  <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
	  <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
	  <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Kaleido.Samples.PriorAuth.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
