<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../build/packages.props" />

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\Abstractions\Kaleido.Abstractions.csproj" />
	  <ProjectReference Include="..\..\Core\Kaleido\Kaleido.csproj" />
	  <ProjectReference Include="..\AspNetCore.Abstractions\Kaleido.Queryable.AspNetCore.Abstractions.csproj" />
	</ItemGroup>

</Project>
