<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.*" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.*" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.*" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Kaleido\Kaleido.csproj" />
		<ProjectReference Include="..\..\src\Kaleido.Provider.SQLite\Kaleido.Provider.SQLite.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Using Include="Kaleido.Queryable" />
		<Using Include="Kaleido.Queryable.Attributes" />
		<Using Include="Kaleido.Queryable.Query" />
	</ItemGroup>
</Project>
