<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
	<UserSecretsId>881f97fb-ace0-4c81-b246-4d08cd688c0f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Swashbuckle.AspNetCore" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	  <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Kaleido.Samples.PriorAuth.Common.csproj" />
    <ProjectReference Include="..\..\..\..\src\Kaleido.Http\Kaleido.Http.csproj" />
    <ProjectReference Include="..\..\..\..\src\Kaleido.Observability.OpenTelemetry\Kaleido.Observability.OpenTelemetry.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Using Include="Kaleido.Queryable" />
		<Using Include="Kaleido.Queryable.Query" />
	</ItemGroup>
</Project>
