<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
	  <UserSecretsId>545800a4-32df-4488-be58-4b1131fe009b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.*" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.*" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Kaleido.Http\Kaleido.Http.csproj" />
    <ProjectReference Include="..\..\..\..\src\Kaleido.Observability.OpenTelemetry\Kaleido.Observability.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\Common\Kaleido.Samples.PriorAuth.Common.csproj" />
  </ItemGroup>

</Project>
