<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
		<RootNamespace>Kaleido.Samples.ECommerce.Data</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Kaleido\Kaleido.csproj" />
	  <ProjectReference Include="..\Data\Kaleido.Samples.ECommerce.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Kaleido.Queryable" />
		<Using Include="Kaleido.Queryable.Query" />
	</ItemGroup>
</Project>
