<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
		<RootNamespace>Kaleido.Samples.ECommerce.Data</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Kaleido\Kaleido.csproj" />
	  <ProjectReference Include="..\Data\Kaleido.Samples.ECommerce.Data.csproj" />
	</ItemGroup>

</Project>
